name: 'Auto Merge Dependency Updates'
description: 'Automatically merge a PR that only contains dependency updates, based on some rules.'
author: 'Tom Jenkinson'
inputs:
  repo-token:
    description: 'GitHub API token'
    default: ${{ github.token }}
  allowed-actors:
    required: true
    description: 'Comma separated list of usernames auto merge is allowed for'
  allowed-update-types:
    description: 'Comma separated list of types of updates that are allowed. Supported: [devDependencies|dependencies]:[major|minor|patch]'
    default: 'devDependencies:minor, devDependencies:patch'
  approve:
    description: 'Automatically approve the PR if it qualifies for auto merge'
    default: 'true'
  merge:
    description: 'Merge the PR if it qualifies'
    default: 'true'
  merge-method:
    description: 'Merge method to use. Supported: "merge", "squash", "rebase"'
    default: 'merge'
  package-block-list:
    required: false
    description: 'Comma separated list of packages that auto merge should not be allowed for'
  package-allow-list:
    required: false
    description: 'Comma separated list of packages that auto merge should only be allowed for. Omit to allow all packages'
outputs:
  success:
    description: '"true" if the commit meets the criteria'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'blue'
